# This file is generated by cargo_embargo.
# Do not modify this file after the LOCAL_DIR line
# because the changes will be overridden on upgrade.
# Content before the first line starting with LOCAL_DIR is preserved.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := proc_macro2
MODULE_RUST_CRATE_TYPES := rlib
MODULE_SRCS := $(LOCAL_DIR)/src/lib.rs
MODULE_RUST_EDITION := 2021
MODULE_RUSTFLAGS += \
	--cfg 'feature="default"' \
	--cfg 'feature="proc-macro"' \
	--cfg 'feature="span-locations"' \
	--cfg 'proc_macro_span' \
	--cfg 'span_locations' \
	--cfg 'wrap_proc_macro'

MODULE_LIBRARY_DEPS := \
	$(call FIND_CRATE,unicode-ident)

include make/library.mk
