# This file is generated by cargo_embargo.
# Do not modify this file after the LOCAL_DIR line
# because the changes will be overridden on upgrade.
# Content before the first line starting with LOCAL_DIR is preserved.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := der
MODULE_RUST_CRATE_TYPES := rlib
MODULE_SRCS := $(LOCAL_DIR)/src/lib.rs
MODULE_RUST_EDITION := 2021
MODULE_RUSTFLAGS += \
	--cfg 'feature="alloc"' \
	--cfg 'feature="derive"' \
	--cfg 'feature="flagset"' \
	--cfg 'feature="oid"' \
	--cfg 'feature="zeroize"'

MODULE_LIBRARY_DEPS := \
	$(call FIND_CRATE,const-oid) \
	$(call FIND_CRATE,der_derive) \
	$(call FIND_CRATE,flagset) \
	$(call FIND_CRATE,zeroize)

include make/library.mk
