[package]
name = "android-pseudo-crate"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
ahash = "=0.8.11"
aho-corasick = "=0.7.20"
android_log-sys = "=0.3.1"
android_logger = "=0.13.3"
anes = "=0.2.0"
annotate-snippets = "=0.9.2"
anyhow = "=1.0.79"
argh = "=0.1.12"
argh_derive = "=0.1.12"
argh_shared = "=0.1.12"
arrayvec = "=0.7.6"
ash = "=0.37.3"
async-stream = "=0.3.5"
async-stream-impl = "=0.3.5"
async-task = "=4.5.0"
async-trait = "=0.1.74"
atomic = "=0.6.0"
atty = "=0.2.14"
axum = "=0.6.20"
base64 = "=0.22.0"
bencher = "=0.1.5"
bincode = "=1.3.3"
bitreader = "=0.3.8"
bstr = "=1.3.0"
buddy_system_allocator = "=0.9.0"
bytemuck_derive = "=1.5.0"
byteorder = "=1.4.3"
bytes = "=1.5.0"
camino = "=1.1.6"
cast = "=0.3.0"
cesu8 = "=1.1.0"
cexpr = "=0.6.0"
cfg-if = "=1.0.0"
ciborium = "=0.2.2"
ciborium-io = "=0.2.2"
ciborium-ll = "=0.2.2"
clap_complete = "=4.4.9"
clap_derive = "=4.2.0"
clap_lex = "=0.3.2"
combine = "=4.6.6"
command-fds = "=0.3.0"
const-oid = "=0.9.6"
coset = "=0.3.7"
crc32fast = "=1.3.2"
criterion = "=0.4.0"
criterion-plot = "=0.5.0"
crossbeam-channel = "=0.5.11"
crossbeam-deque = "=0.8.5"
crossbeam-epoch = "=0.9.18"
crossbeam-queue = "=0.3.11"
crossbeam-utils = "=0.8.19"
darling_core = "=0.20.8"
darling_macro = "=0.20.8"
dashmap = "=5.5.3"
data-encoding = "=2.5.0"
der = "=0.7.8"
der_derive = "=0.7.2"
derive_arbitrary = "=1.3.2"
displaydoc = "=0.2.4"
document-features = "=0.2.8"
downcast-rs = "=1.2.0"
drm = "=0.11.1"
either = "=1.9.0"
enumn = "=0.1.8"
env_logger = "=0.10.0"
epoll = "=4.3.3"
errno = "=0.3.8"
fallible-iterator = "=0.2.0"
fallible-streaming-iterator = "=0.1.9"
fastrand = "=1.9.0"
flagset = "=0.4.3"
fragile = "=2.0.0"
fs-err = "=2.11.0"
futures = "=0.3.30"
futures-core = "=0.3.30"
futures-executor = "=0.3.30"
futures-io = "=0.3.30"
futures-macro = "=0.3.30"
futures-sink = "=0.3.30"
futures-task = "=0.3.30"
futures-test = "=0.3.30"
futures-util = "=0.3.30"
gbm = "=0.14.2"
getrandom = "=0.2.12"
glob = "=0.3.1"
googletest = "=0.11.0"
googletest_macro = "=0.11.0"
h2 = "=0.4.4"
hashbrown = "=0.12.3"
hashlink = "=0.8.1"
http-body = "=0.4.6"
httparse = "=1.8.0"
httpdate = "=1.0.3"
idna = "=0.5.0"
instant = "=0.1.12"
intrusive-collections = "=0.9.6"
itertools = "=0.13.0"
jni-sys = "=0.3.0"
lazy_static = "=1.4.0"
libc = "=0.2.153"
libloading = "=0.8.3"
linked-hash-map = "=0.5.6"
linkme = "=0.3.10"
litrs = "=0.3.0"
lock_api = "=0.4.11"
log = "=0.4.17"
lru-cache = "=0.1.2"
lz4_flex = "=0.11.2"
macaddr = "=1.0.1"
managed = "=0.8.0"
maybe-async = "=0.2.10"
memchr = "=2.7.1"
memoffset = "=0.9.0"
miette = "=5.10.0"
mime = "=0.3.17"
mio = "=0.8.6"
mls-rs-codec = "=0.5.3"
mls-rs-codec-derive = "=0.1.1"
mls-rs-core = "=0.18.0"
mockall = "=0.12.1"
named-lock = "=0.3.0"
no-panic = "=0.1.26"
nom = "=7.1.3"
num-integer = "=0.1.45"
num-traits = "=0.2.19"
num_cpus = "=1.16.0"
oorandom = "=11.1.3"
os_str_bytes = "=6.4.1"
p9 = "=0.2.3"
p9_wire_format_derive = "=0.2.3"
parking_lot = "=0.12.1"
parking_lot_core = "=0.9.9"
pathdiff = "=0.2.1"
pdl-runtime = "=0.3.1"
pest = "=2.7.6"
pest_derive = "=2.7.6"
pest_generator = "=2.7.6"
pest_meta = "=2.7.6"
pin-project = "=1.1.3"
pin-project-internal = "=1.1.3"
pin-project-lite = "=0.2.13"
pkcs1 = "=0.7.5"
pkcs8 = "=0.10.2"
plotters-backend = "=0.3.5"
plotters-svg = "=0.3.5"
ppv-lite86 = "=0.2.17"
predicates-core = "=1.0.6"
predicates-tree = "=1.0.9"
prettyplease = "=0.2.6"
proc-macro2 = "=1.0.69"
rand = "=0.8.5"
rand_chacha = "=0.3.1"
rand_core = "=0.6.4"
rand_xorshift = "=0.3.0"
rayon = "=1.8.1"
rayon-core = "=1.12.1"
regex = "=1.7.3"
regex-syntax = "=0.6.29"
rusqlite = "=0.29.0"
rustc-demangle = "=0.1.23"
rustc-hash = "=1.1.0"
rustversion = "=1.0.14"
scopeguard = "=1.2.0"
sec1 = "=0.7.3"
semver = "=1.0.21"
serde_cbor = "=0.11.2"
serde_derive = "=1.0.158"
shared_library = "=0.1.9"
slab = "=0.4.9"
smallvec = "=1.13.1"
smccc = "=0.1.1"
socket2 = "=0.5.5"
spin = "=0.9.8"
spki = "=0.7.3"
strsim = "=0.11.0"
strum = "=0.25.0"
strum_macros = "=0.25.3"
syn-mid = "=0.6.0"
sync_wrapper = "=1.0.1"
synstructure = "=0.12.6"
tempfile = "=3.3.0"
termcolor = "=1.4.1"
termtree = "=0.4.1"
textwrap = "=0.16.0"
thiserror = "=1.0.49"
thread_local = "=1.1.7"
tinytemplate = "=1.2.1"
tokio-macros = "=2.1.0"
tokio-stream = "=0.1.14"
url = "=2.3.1"
zeroize = "=1.6.0"
zeroize_derive = "=1.4.2"
zip = "=0.6.6"
