[package]
name = "android-pseudo-crate"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
# go/keep-sorted start
aarch64-paging = "=0.7.0"
acpi = "=5.2.0"
adler2 = "=2.0.1"
ahash = "=0.8.11"
aho-corasick = "=1.1.3"
android_bp = "=0.3.0"
android_log-sys = "=0.3.2"
android_logger = "=0.15.0"
anes = "=0.2.1"
annotate-snippets = "=0.11.5"
anstyle = "=1.0.11"
anyhow = "=1.0.99"
arbitrary = "=1.4.1"
arc-swap = "=1.7.1"
argh = "=0.1.12"
argh_derive = "=0.1.12"
argh_shared = "=0.1.13"
arrayvec = "=0.7.6"
ash = "=0.37.3"
async-stream = "=0.3.6"
async-stream-impl = "=0.3.6"
async-task = "=4.7.1"
async-trait = "=0.1.88"
atomic = "=0.6.1"
atty = "=0.2.14"
axum = "=0.6.20"
axum-core = "=0.3.4"
base64 = "=0.22.1"
bencher = "=0.1.5"
bincode = "=1.3.3"
bindgen = "=0.72.0"
bindgen-cli = "=0.72.0"
bit_field = "=0.10.2"
bitflags = "=2.9.1"
bitreader = "=0.3.11"
bitvec = "=1.0.1"
bstr = "=1.12.0"
buddy_system_allocator = "=0.11.0"
bytemuck = "=1.23.1"
bytemuck_derive = "=1.10.1"
byteorder = "=1.5.0"
byteorder-lite = "=0.1.0"
bytes = "=1.10.1"
camino = "=1.1.11"
caps = "=0.5.5"
cargo-platform = "=0.3.0"
cargo_metadata = "=0.19.2"
cargo_toml = "=0.22.1"
cast = "=0.3.0"
cesu8 = "=1.1.0"
cexpr = "=0.6.0"
cfg-expr = "=0.20.2"
cfg-if = "=1.0.1"
chrono = "=0.4.39"
chunked_transfer = "=1.5.0"
ciborium = "=0.2.2"
ciborium-io = "=0.2.2"
ciborium-ll = "=0.2.2"
cidr = "=0.3.1"
clang-sys = "=1.8.1"
clap = "4.5.0"
clap_builder = "=4.5.0"
clap_complete = "=4.5.3"
clap_derive = "=4.5.0"
clap_lex = "=0.7.5"
codespan-reporting = "=0.11.1"
combine = "=4.6.7"
command-fds = "=0.3.0"
config = "=0.13.4"
configparser = "=3.1.0"
const-oid = "=0.10.1"
coset = "=0.3.8"
cov-mark = "=2.0.0"
crates-index = "=3.10.0"
crc = "=3.3.0"
crc-catalog = "=2.4.0"
crc32fast = "=1.5.0"
criterion = "=0.4.0"
criterion-plot = "=0.6.0"
critical-section = "=1.2.0"
crossbeam-channel = "=0.5.15"
crossbeam-deque = "=0.8.6"
crossbeam-epoch = "=0.9.18"
crossbeam-queue = "=0.3.12"
crossbeam-utils = "=0.8.21"
csv = "=1.3.1"
csv-core = "=0.1.12"
darling = "0.20.10"
darling_core = "=0.20.10"
darling_macro = "=0.20.10"
dashmap = "=5.5.3"
dasp_sample = "=0.11.0"
data-encoding = "=2.9.0"
dc_bundle = "=0.37.2"
dc_layout = "=0.37.2"
debug_tree = "=0.4.0"
der = "=0.7.10"
der_derive = "=0.7.3"
derive-where = "=1.6.0"
derive_arbitrary = "=1.4.1"
derive_builder = "=0.20.2"
derive_builder_core = "=0.20.2"
derive_builder_macro = "=0.20.2"
diplomat = "=0.10.0"
diplomat-runtime = "=0.12.0"
diplomat_core = "=0.10.0"
displaydoc = "=0.2.5"
doc-comment = "=0.3.3"
document-features = "=0.2.11"
downcast = "=0.11.0"
downcast-rs = "=2.0.1"
drm = "=0.14.1"
drm-ffi = "=0.9.0"
drm-fourcc = "=2.2.0"
dyn-clone = "=1.0.20"
either = "=1.15.0"
elf = "=0.8.0"
enum-as-inner = "=0.6.1"
enum-primitive-derive = "=0.3.0"
enumn = "=0.1.14"
env_filter = "=0.1.3"
env_logger = "=0.10.2"
epoll = "=4.4.0"
equivalent = "=1.0.2"
errno = "=0.3.13"
etherparse = "=0.19.0"
evdev = "=0.13.1"
fallible-iterator = "=0.3.0"
fallible-streaming-iterator = "=0.1.9"
fastrand = "=2.3.0"
fdeflate = "=0.3.7"
filetime = "=0.2.25"
fixedbitset = "=0.5.7"
flagset = "=0.4.7"
flate2 = "=1.1.2"
fnv = "=1.0.7"
foldhash = "=0.1.5"
font-types = "=0.9.0"
foreign-types = "=0.3.2"
foreign-types-shared = "=0.1.1"
form_urlencoded = "=1.2.1"
fragile = "=2.0.1"
fs-err = "=3.1.1"
funty = "=2.0.0"
futures = "=0.3.31"
futures-channel = "=0.3.31"
futures-core = "=0.3.31"
futures-executor = "=0.3.31"
futures-io = "=0.3.31"
futures-macro = "=0.3.31"
futures-sink = "=0.3.31"
futures-task = "=0.3.31"
futures-test = "=0.3.31"
futures-util = "=0.3.31"
fxhash = "=0.2.1"
gbm = "=0.15.0"
gdbstub = "=0.7.6"
gdbstub_arch = "=0.3.2"
getrandom = "=0.3.3"
gl = "=0.14.0"
gl_common = "=0.1.0"
glam = "=0.30.5"
glob = "=0.3.2"
googletest = "=0.13.0"
googletest_macro = "=0.13.0"
gpio-cdev = "=0.6.0"
grid = "=0.18.0"
grpcio = "=0.13.0"
grpcio-compiler = "=0.13.0"
grpcio-sys = "=0.13.0"
h2 = "=0.4.4"
half = "=2.2.1"
handlebars = "=6.3.2"
hashbrown = "=0.15.5"
hashlink = "=0.10.0"
heck = "=0.5.0"
hex = "=0.4.3"
home = "=0.5.11"
hound = "=3.5.1"
http = "=1.3.1"
http-body = "=0.4.6"
httparse = "=1.10.1"
httpdate = "=1.0.3"
hyper = "=0.14.32"
hyper-timeout = "=0.4.1"
icu_capi = "=2.0.0-beta2"
icu_casemap = "=2.0.0-beta2"
icu_casemap_data = "=2.0.0-beta2"
icu_collections = "=2.0.0-beta2"
icu_locale = "=2.0.0-beta2"
icu_locale_core = "=2.0.0-beta2"
icu_locale_data = "=2.0.0-beta2"
icu_properties = "=2.0.0-beta2"
icu_properties_data = "=2.0.0-beta2"
icu_provider = "=2.0.0-beta2"
icu_provider_adapters = "=2.0.0-beta2"
icu_provider_baked = "=2.0.0-beta2"
ident_case = "=1.0.1"
idna = "=0.5.0"
image = "=0.25.6"
indexmap = "=1.9.3"
inotify = "=0.11.0"
inotify-sys = "=0.1.5"
intrusive-collections = "=0.9.7"
ipnet = "=2.11.0"
ipp = "=5.3.1"
ippusb = "=0.5.0"
is-terminal = "=0.4.16"
itertools = "=0.14.0"
itoa = "=1.0.15"
jni = "=0.21.1"
jni-sys = "=0.3.0"
json-strip-comments = "=1.0.4"
kernlog = "=0.3.1"
khronos = "=0.1.2"
khronos-egl = "=6.0.0"
kobject-uevent = "=0.2.0"
lazy_static = "=1.4.0"
lazycell = "=1.3.0"
libbpf-rs = "=0.24.8"
libbpf-sys = "=1.4.3"
libbz2-rs-sys = "=0.2.1"
libc = "=0.2.171"
libfuzzer-sys = "=0.4.8"
libloading = "=0.8.8"
libm = "=0.2.11"
libsqlite3-sys = "=0.30.1"
libtest-mimic = "=0.6.1"
libusb1-sys = "=0.7.0"
libz-rs-sys = "=0.5.1"
libz-sys = "=1.1.22"
linked-hash-map = "=0.5.6"
linkme = "=0.3.31"
linkme-impl = "=0.3.31"
litemap = "=0.7.5"
litrs = "=0.5.1"
lock_api = "=0.4.13"
log = "=0.4.27"
lru-cache = "=0.1.2"
lz4_flex = "=0.11.5"
macaddr = "=1.0.1"
managed = "=0.8.0"
maplit = "=1.0.2"
matches = "=0.1.10"
matchit = "=0.7.3"
maybe-async = "=0.2.10"
memchr = "=2.7.5"
memmap2 = "=0.9.7"
memoffset = "=0.9.1"
merge = "=0.1.0"
merge_derive = "=0.1.0"
miette = "=7.6.0"
miette-derive = "=7.6.0"
mime = "=0.3.17"
minimal-lexical = "=0.2.1"
miniz_oxide = "=0.8.9"
mio = "=1.0.3"
mls-rs = "=0.39.4"
mls-rs-codec = "=0.6.0"
mls-rs-codec-derive = "=0.2.0"
mls-rs-core = "=0.18.1"
mls-rs-crypto-traits = "=0.10.0"
mockall = "=0.13.1"
mockall_derive = "=0.13.1"
mockall_double = "=0.3.1"
moveit = "=0.6.0"
named-lock = "=0.4.1"
netlink-packet-core = "=0.7.0"
netlink-packet-route = "=0.24.0"
netlink-packet-utils = "=0.5.2"
netlink-proto = "=0.11.5"
netlink-sys = "=0.8.7"
nix = "=0.29.0"
no-panic = "=0.1.35"
nom = "=7.1.3"
num-bigint = "=0.4.6"
num-complex = "=0.4.6"
num-derive = "=0.4.2"
num-integer = "=0.1.46"
num-modular = "=0.6.1"
num-order = "=1.2.0"
num-traits = "=0.2.19"
num_cpus = "=1.16.0"
num_enum = "=0.7.3"
num_enum_derive = "=0.7.3"
octets = "=0.3.0"
once_cell = "=1.21.3"
oorandom = "=11.1.5"
open-enum = "=0.5.2"
open-enum-derive = "=0.5.2"
openssl-macros = "=0.1.1"
os_pipe = "=1.2.2"
os_str_bytes = "=6.6.1"
p9 = "=0.2.3"
p9_wire_format_derive = "=0.2.3"
parking_lot = "=0.12.4"
parking_lot_core = "=0.9.11"
paste = "=1.0.15"
pathdiff = "=0.2.3"
pdl-compiler = "=0.3.3"
pdl-runtime = "=0.3.3"
percent-encoding = "=2.3.1"
percore = "=0.2.1"
pest = "=2.8.1"
pest_derive = "=2.8.1"
pest_generator = "=2.8.1"
pest_meta = "=2.8.1"
petgraph = "=0.6.5"
pin-project = "=1.1.8"
pin-project-internal = "=1.1.8"
pin-project-lite = "=0.2.16"
pin-utils = "=0.1.0"
pkcs1 = "=0.7.5"
pkcs8 = "=0.10.2"
plotters = "=0.3.7"
plotters-backend = "=0.3.7"
plotters-svg = "=0.3.7"
png = "=0.17.16"
poll_token_derive = "=0.1.0"
portable-atomic = "=1.11.1"
potential_utf = "=0.1.2"
ppv-lite86 = "=0.2.21"
predicates = "=3.1.3"
predicates-core = "=1.0.9"
predicates-tree = "=1.0.11"
prettyplease = "=0.2.36"
proc-macro2 = "=1.0.96"
protobuf = "=3.2.0"
protobuf-codegen = "=3.2.0"
protobuf-json-mapping = "=3.2.0"
protobuf-parse = "=3.2.0"
protobuf-support = "=3.2.0"
ptr_meta = "=0.3.0"
ptr_meta_derive = "=0.3.0"
quiche = "=0.17.1"
quickcheck = "=1.0.3"
quote = "=1.0.40"
radium = "=0.7.0"
rand = "=0.9.2"
rand_chacha = "=0.9.0"
rand_core = "=0.9.3"
rand_xorshift = "=0.4.0"
rayon = "=1.10.0"
rayon-core = "=1.12.1"
read-fonts = "=0.31.1"
regex = "=1.11.1"
regex-automata = "=0.4.9"
regex-syntax = "=0.8.5"
remain = "=0.2.15"
ring = "=0.17.2"
rtnetlink = "=0.17.0"
rusb = "=0.9.4"
rusqlite = "=0.32.1"
rustc-demangle = "=0.1.26"
rustc-demangle-capi = "=0.1.0"
rustc-hash = "=2.1.1"
rustc-stable-hash = "=0.1.2"
rustix = "=1.0.7"
rustversion = "=1.0.21"
ryu = "=1.0.20"
safe-mmio = "=0.2.5"
same-file = "=1.0.6"
scopeguard = "=1.2.0"
sec1 = "=0.7.3"
selinux = "=0.5.0"
selinux-sys = "=0.6.13"
semver = "=1.0.26"
serde = "=1.0.219"
serde-xml-rs = "=0.6.0"
serde_bytes = "=0.11.17"
serde_cbor = "=0.11.2"
serde_derive = "=1.0.219"
serde_json = "=1.0.142"
serde_spanned = "=0.6.9"
serde_test = "=1.0.177"
serde_yaml = "=0.9.34"
serialport = "=4.7.2"
sharded-slab = "=0.1.7"
shared_child = "=1.0.2"
shared_library = "=0.1.9"
shlex = "=1.3.0"
signal-hook = "=0.3.18"
signal-hook-registry = "=1.4.6"
simd-adler32 = "=0.3.7"
siphasher = "=1.0.1"
skrifa = "=0.33.1"
slab = "=0.4.11"
slotmap = "=1.0.7"
smallvec = "=1.15.1"
smccc = "=0.2.2"
smol_str = "=0.3.2"
socket2 = "=0.5.10"
spdx = "=0.11.0"
spidev = "=0.7.0"
spin = "=0.10.0"
spki = "=0.7.3"
stable_deref_trait = "=1.2.0"
static_assertions = "=1.1.0"
strck = "=1.0.0"
strsim = "=0.11.1"
strum = "=0.27.2"
strum_macros = "=0.27.0"
syn = "=2.0.104"
syn-mid = "=0.6.0"
sync_wrapper = "=1.0.2"
synstructure = "=0.13.2"
taffy = "=0.7.7"
tap = "=1.0.1"
tar = "=0.4.44"
tempfile = "=3.12.0"
termcolor = "=1.4.1"
termtree = "=0.4.1"
textdistance = "=1.1.1"
textwrap = "=0.16.2"
thiserror = "=2.0.12"
thiserror-impl = "=2.0.12"
thread-priority = "=2.1.0"
thread_local = "=1.1.9"
threadpool = "=1.8.1"
tikv-jemalloc-sys = "=0.5.4"
tikv-jemallocator = "=0.5.4"
tinyjson = "=2.5.1"
tinystr = "=0.8.1"
tinytemplate = "=1.2.1"
tinyvec = "=1.6.0"
tinyvec_macros = "=0.1.1"
tokio = "=1.45.1"
tokio-io-timeout = "=1.2.1"
tokio-macros = "=2.5.0"
tokio-openssl = "=0.6.5"
tokio-stream = "=0.1.17"
tokio-test = "=0.4.2"
tokio-util = "=0.7.16"
toml = "=0.8.19"
toml_datetime = "=0.6.11"
toml_edit = "=0.22.20"
tonic = "=0.11.0"
tower = "=0.4.13"
tower-layer = "=0.3.3"
tower-service = "=0.3.3"
tracing = "=0.1.41"
tracing-attributes = "=0.1.28"
tracing-core = "=0.1.34"
tracing-subscriber = "=0.3.19"
try-lock = "=0.2.5"
tungstenite = "=0.27.0"
twox-hash = "=2.1.1"
ucd-trie = "=0.1.7"
ucs2 = "=0.3.3"
uefi = "=0.35.0"
uefi-macros = "=0.18.1"
uefi-raw = "=0.11.0"
uguid = "=2.2.0"
unicode-bidi = "=0.3.15"
unicode-ident = "=1.0.8"
unicode-normalization = "=0.1.24"
unicode-segmentation = "=1.12.0"
unicode-width = "=0.2.1"
unicode-xid = "=0.2.6"
unsafe-libyaml = "=0.2.11"
untrusted = "=0.7.1"
url = "=2.5.2"
userfaultfd = "=0.8.1"
userfaultfd-sys = "=0.5.0"
utf-8 = "=0.7.6"
uuid = "=1.12.1"
vhost = "=0.13.0"
vhost-user-backend = "=0.17.0"
virtio-bindings = "=0.2.4"
virtio-drivers = "=0.9.0"
virtio-drivers-and-devices = "=0.2.3"
virtio-queue = "=0.14.0"
virtio-vsock = "=0.8.0"
vm-memory = "=0.16.2"
vmm-sys-util = "=0.12.1"
vsock = "=0.5.1"
vsprintf = "=2.0.0"
vulkano = "=0.33.0"
walkdir = "=2.5.0"
want = "=0.3.1"
weak-table = "=0.3.2"
webpki = "=0.22.4"
which = "=4.4.0"
winnow = "=0.6.26"
writeable = "=0.6.1"
wyz = "=0.5.1"
x509-cert = "=0.2.5"
xml-rs = "=0.8.19"
yaml-rust = "=0.4.5"
yoke = "=0.8.0"
yoke-derive = "=0.8.0"
zerocopy = "=0.8.26"
zerocopy-derive = "=0.8.26"
zerofrom = "=0.1.6"
zerofrom-derive = "=0.1.6"
zeroize = "=1.8.1"
zeroize_derive = "=1.4.2"
zerotrie = "=0.2.2"
zerovec = "=0.11.4"
zerovec-derive = "=0.11.1"
zip = "=0.6.6"
zlib-rs = "=0.5.1"
# go/keep-sorted end
