[package]
name = "android-pseudo-crate"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
ahash = "=0.8.11"
aho-corasick = "=0.7.20"
android_log-sys = "=0.3.1"
android_logger = "=0.13.3"
anes = "=0.2.0"
annotate-snippets = "=0.9.2"
anyhow = "=1.0.79"
argh = "=0.1.12"
argh_derive = "=0.1.12"
argh_shared = "=0.1.12"
ash = "=0.37.3"
async-stream = "=0.3.5"
async-stream-impl = "=0.3.5"
async-task = "=4.5.0"
async-trait = "=0.1.74"
atomic = "=0.6.0"
atty = "=0.2.14"
axum = "=0.6.20"
base64 = "=0.22.0"
bencher = "=0.1.5"
bincode = "=1.3.3"
bitreader = "=0.3.8"
bstr = "=1.3.0"
buddy_system_allocator = "=0.9.0"
byteorder = "=1.4.3"
bytes = "=1.5.0"
camino = "=1.1.6"
cast = "=0.3.0"
cesu8 = "=1.1.0"
cexpr = "=0.6.0"
cfg-if = "=1.0.0"
ciborium = "=0.2.2"
ciborium-io = "=0.2.2"
ciborium-ll = "=0.2.2"
clap_complete = "=4.4.9"
clap_derive = "=4.2.0"
clap_lex = "=0.3.2"
combine = "=4.6.6"
command-fds = "=0.3.0"
const-oid = "=0.9.6"
coset = "=0.3.7"
crc32fast = "=1.3.2"
criterion = "=0.4.0"
criterion-plot = "=0.5.0"
crossbeam-channel = "=0.5.11"
crossbeam-deque = "=0.8.5"
crossbeam-epoch = "=0.9.18"
crossbeam-queue = "=0.3.11"
crossbeam-utils = "=0.8.19"
darling_core = "=0.20.8"
darling_macro = "=0.20.8"
dashmap = "=5.5.3"
data-encoding = "=2.5.0"
der = "=0.7.8"
der_derive = "=0.7.2"
derive_arbitrary = "=1.3.2"
displaydoc = "=0.2.4"
document-features = "=0.2.8"
downcast-rs = "=1.2.0"
drm = "=0.11.1"
either = "=1.9.0"
enumn = "=0.1.8"
